# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_right', models.ImageField(blank=True, null=True, upload_to='exhibition_preview')),
                ('preview_left', models.ImageField(blank=True, null=True, upload_to='exhibition_preview')),
                ('preview_top', models.ImageField(blank=True, null=True, upload_to='exhibition_preview')),
                ('preview_bottom', models.ImageField(blank=True, null=True, upload_to='exhibition_preview')),
                ('preview_front', models.ImageField(blank=True, null=True, upload_to='exhibition_preview')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
