# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
