# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='preview_back',
            field=models.ImageField(blank=True, null=True, upload_to='exhibition_preview'),
        ),
    ]
